name: 'Generate Nextcloud test matrix'
description: 'Generate a test matrix with Nextcloud and PHP versions based on version ranges'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  min-php-version:
    description: 'Minimum PHP version to test'
    required: true
  max-php-version:
    description: 'Maximum PHP version to test'
    required: true
  min-nextcloud-version:
    description: 'Minimum Nextcloud version to test'
    required: false
    default: 'master'
  max-nextcloud-version:
    description: 'Maximum Nextcloud version to test'
    required: false
    default: 'master'
runs:
  using: 'node16'
  main: 'index.js'
